name: data-forest
version: 0.1.0.6
category: Data Structures

synopsis: >
  A simple multi-way tree data structure.

description: >
  In some contexts, forests (collections of zero or more trees) are more
  important than trees. The /data-forest/ library provides a @Tree@ type much
  like the one from the popular /containers/ library, but it also provides a
  @Forest@ type with its own @Functor@ and @Foldable@ instances.

library:
  source-dirs: src
  exposed-modules:
    - Data.Forest

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/data-forest

license:      Apache-2.0
license-file: license.txt

dependencies:
  - base >= 4.9 && < 4.12

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
      - data-forest
